@startuml
hide circles


!startsub PriceableElement
package PriceCalculator
{
    package PriceableElements
    {
        abstract class PriceableElement
        {
            +getPrice(valuationDate: Date, market: Market)
        }
    }
}
!endsub


!startsub CashFlow
package PriceCalculator
{
    package PriceableElements
    {
        abstract class CashFlow
        {
            {abstract} +getPaymentDates(): Date[0..*]
            {abstract} +getPaymentAmount(paymentDate: Date, market: Market)
        }
    }
}
!endsub


!startsub Derivative
package PriceCalculator
{
    package PriceableElements
    {
        abstract class Derivative
        {
            +getPrice(valuationDate: Date, market: Market)
            {abstract} +getBasePrice(valuationDate: Date, pricer: Pricer)
            {static} +setPricerCreator(newPricerCreator: PricerFactory)
        }
    }
}
!endsub



!startsub Pricer
package PriceCalculator
{
    package PriceableElements
    {
        abstract class Pricer
        {
            {abstract} +getDiscountFactor(valuationDate: Date, maturityDate: Date)
            {abstract} +getCallOptionBasePrice(underlyings, strike, valuationDate: Date, maturityDate: Date)
            {abstract} +getBasePrice(pricedElement: CashFlow, valuationDate: Date)
        }
    }
}
!endsub


!startsub Market
package PriceCalculator
{
    package PriceableElements
    {
        abstract class Market
        {
            {abstract} +getQuotes(ticker, observationDates: Date[1..*])
        }
    }
}
!endsub


!startsub PricerFactory
package PriceCalculator
{
    package PriceableElements
    {
        abstract class PricerFactory
        {
            {static} {abstract} +createPricer(underlyings, valuationDate: Date, market: Market): Pricer
        }
    }
}
!endsub


!startsub VanillaStructuredProduct
package PriceCalculator
{
    package PriceableElements
    {
        class VanillaStructuredProduct
        {
            +getPaymentDates(): Date[0..*]
            +getPaymentAmount(paymentDate: Date, market: Market)
            +getBasePrice(valuationDate: Date, pricer: Pricer)
        }
    }
}
!endsub


!startsub Autocall
package PriceCalculator
{
    package PriceableElements
    {
        class Autocall
        {
            +getPaymentDates(): Date[0..*]
            +getPaymentAmount(paymentDate: Date, market: Market)
            +getBasePrice(valuationDate: Date, pricer: Pricer)
        }
    }
}
!endsub


PriceableElement ..> Market
Derivative --> "pricerCreator" PricerFactory: <<static>>
Derivative -up-|> PriceableElement
Derivative ..> Pricer
Pricer -up..> CashFlow
VanillaStructuredProduct -up-|> CashFlow
VanillaStructuredProduct -up-|> Derivative
Autocall -up-|> CashFlow
Autocall -up-|> Derivative
PricerFactory ..> Pricer
PricerFactory ..> Market


@enduml
