@startuml
hide circles

!includesub PriceableElements.puml!Pricer
!includesub PriceableElements.puml!Market
!includesub PriceableElements.puml!PricerFactory


!startsub Simulations
package PriceCalculator
{
    package PriceCalculators
    {
        class Simulations
        {
        }
    }
}
!endsub


!startsub SimulatedMarket
package PriceCalculator
{
    package PriceCalculators
    {
        class SimulatedMarket
        {
            -simulationIndex
            +getQuote(ticker, observationDate: Date)
        }
    }
}
!endsub


!startsub SamplePricer
package PriceCalculator
{
    package PriceCalculators
    {
        class SamplePricer
        {
        }
        SamplePricer -up--|> Pricer
    }
}
!endsub


!startsub SimulationPricer
package PriceCalculator
{
    package PriceCalculators
    {
        class SimulationPricer
        {
            {static} +createPricer(underlyings, valuationDate: Date, market: Market): Pricer
            {static} +create(market: Market)
            +getBasePrice(pricedElement: CashFlow, valuationDate: Date)
        }
    }
}
!endsub


SimulatedMarket -up--|> Market
SimulatedMarket -up--> "originalMarket" Market
SimulatedMarket --> "amendment" Simulations
SimulationPricer -up--|> Pricer
SimulationPricer --|> PricerFactory
SimulationPricer --> Market
SimulationPricer --> SamplePricer
SimulationPricer ..> Simulations
SimulationPricer ..> SimulatedMarket


@enduml
