@startuml
hide circles

!includesub PriceableElements.puml!Pricer
!includesub PriceableElements.puml!QuoteProvider
!includesub PriceableElements.puml!PricerFactory


!startsub Simulation
package PriceCalculator
{
    package Simulation
    {
        abstract class Simulation
        {
            {abstract} +getSimulatedValue(variableName, simulationDate: Date, simulationIndex)
        }
    }
}
!endsub


!startsub GeometricBrownianMotion
package PriceCalculator
{
    package Simulation
    {
        class GeometricBrownianMotion
        {
            {static} +create(variableNames[1..*], observationDate: Date, simulationDates: Date[1..*], initialValues[1..*], drift: DiscountCurve[1..*], covariance: Covariance)
            +getSimulatedValue(variableName, simulationDate: Date, simulationIndex)
        }
    }
}
!endsub


!startsub SimulatedQuoteProvider
package PriceCalculator
{
    package Simulation
    {
        class SimulatedQuoteProvider
        {
            -simulationIndex
            +getQuotes(ticker, observationDates: Date[1..*])
        }
    }
}
!endsub


!startsub Covariance
package PriceCalculator
{
    package Simulation
    {
        abstract class Covariance
        {
            {abstract} +getTotalCovariance(forecastDate: Date)
        }
    }
!endsub


!startsub DiscountCurve
package PriceCalculator
{
    package Simulation
    {
        abstract class DiscountCurve
        {
            {abstract} +getDiscountFactor(paymentDate: Date)
        }
    }
!endsub


!startsub FlatHistoricalCovariance
package PriceCalculator
{
    package Simulation
    {
        class FlatHistoricalCovariance
        {
            {static} +create(underlyings, observationDate: Date, market: Market)
            +getTotalCovariance(forecastDate: Date)
        }
    }
!endsub


!startsub IndexDiscountCurve
package PriceCalculator
{
    package Simulation
    {
        class IndexDiscountCurve
        {
            {static} +create(valuationDate: Date, tenors, tickers, market: Market)
            +getDiscountFactor(paymentDate: Date)
        }
    }
!endsub


!startsub SimulationPricer
package PriceCalculator
{
    package Simulation
    {
        class SimulationPricer
        {
            {static} +createPricer(underlyings, valuationDate: Date, market: QuoteProvider): Pricer
            {static} +create(underlyings, valuationDate: Date, market: QuoteProvider)
            +getBasePrice(pricedElement: CashFlow, valuationDate: Date)
        }
    }
}
!endsub


GeometricBrownianMotion -up-|> Simulation
GeometricBrownianMotion --> "drift" DiscountCurve
GeometricBrownianMotion --> "covariance" Covariance
IndexDiscountCurve -up-|> DiscountCurve
FlatHistoricalCovariance -up-|> Covariance
FlatHistoricalCovariance --> "market" QuoteProvider
SimulatedQuoteProvider -up--|> QuoteProvider
SimulatedQuoteProvider -up--> "originalQuoteProvider" QuoteProvider
SimulatedQuoteProvider --> "amendment" Simulation
SimulationPricer -up--|> Pricer
SimulationPricer --|> PricerFactory
SimulationPricer --> QuoteProvider
SimulationPricer ..> IndexDiscountCurve
SimulationPricer ..> FlatHistoricalCovariance
SimulationPricer --> Simulation
SimulationPricer ..> SimulatedQuoteProvider


@enduml
